# FLASK/GUNICORN PARAMETERS
port: 8000
bind_hosts: 127.0.0.1
workers: 8
threads: 4

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: flask.log # might require absolute path
loglevel: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
logger_name: KackyRecords

kacky_reloaded_club_id: 3074
tmx_update_frequency: 10  # how many minutes between tmx record updates?

num_db_connections: 15
